### ISSUE TITLE
IntelliJ Plugin: Exception Read access is allowed from inside read-action (or EDT) only

### ISSUE THREAD

**Issue by nisrael** [eclipse-scout/scout.sdk#21]
Plugin Version: 13.0.0.23141325
IntelliJ 2023.1.3 Ultimate

The error occurs every few minutes just by editing Java files.
I think that it might occur only since the update to IntelliJ 2023.1.3 (from 2023.1.2).

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[ApplicationImpl pooled thread 716,4,main] 731537416 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1173003057
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:205)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:133)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:125)
	at org.eclipse.scout.sdk.s2i.environment.IdeaEnvironment.findClasspathEntry(IdeaEnvironment.kt:166)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceInputWithIdea.getSourceFolderOf(DerivedResourceInputWithIdea.kt:40)
	at org.eclipse.scout.sdk.core.s.derived.DtoUpdateHandler.writeDerivedTypeOf(DtoUpdateHandler.java:50)
	at org.eclipse.scout.sdk.core.s.derived.DtoUpdateHandler.lambda$execute$0(DtoUpdateHandler.java:40)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at org.eclipse.scout.sdk.core.s.derived.DtoUpdateHandler.execute(DtoUpdateHandler.java:40)
	at org.eclipse.scout.sdk.core.s.derived.AbstractDerivedResourceHandler.apply(AbstractDerivedResourceHandler.java:43)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor$executeHandler$1.invoke(DerivedResourceManagerImplementor.kt:181)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor$executeHandler$1.invoke(DerivedResourceManagerImplementor.kt:179)
	at org.eclipse.scout.sdk.s2i.environment.TransactionManager$Companion.callInExistingTransaction$lambda$0(TransactionManager.kt:87)
	at org.eclipse.scout.sdk.core.util.CoreUtils.callInContext(CoreUtils.java:281)
	at org.eclipse.scout.sdk.s2i.environment.TransactionManager$Companion.callInExistingTransaction(TransactionManager.kt:87)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor.executeHandler(DerivedResourceManagerImplementor.kt:179)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor.executeAllHandlersAndWait(DerivedResourceManagerImplementor.kt:157)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor.performUpdateAsync(DerivedResourceManagerImplementor.kt:127)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor.access$performUpdateAsync(DerivedResourceManagerImplementor.kt:45)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor$scheduleUpdate$1.invoke(DerivedResourceManagerImplementor.kt:112)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor$scheduleUpdate$1.invoke(DerivedResourceManagerImplementor.kt:110)
	at org.eclipse.scout.sdk.s2i.environment.IdeaEnvironment$Factory$callInIdeaEnvironment$job$1$1.invoke(IdeaEnvironment.kt:75)
	at org.eclipse.scout.sdk.s2i.environment.IdeaEnvironment$Factory$callInIdeaEnvironment$job$1$1.invoke(IdeaEnvironment.kt:74)
	at org.eclipse.scout.sdk.s2i.environment.IdeaEnvironment$Factory.callInIdeaEnvironmentSync(IdeaEnvironment.kt:63)
	at org.eclipse.scout.sdk.s2i.environment.IdeaEnvironment$Factory$callInIdeaEnvironment$job$1.invoke(IdeaEnvironment.kt:74)
	at org.eclipse.scout.sdk.s2i.environment.IdeaEnvironment$Factory$callInIdeaEnvironment$job$1.invoke(IdeaEnvironment.kt:73)
	at org.eclipse.scout.sdk.s2i.environment.OperationTask$run$2.invoke(OperationTask.kt:44)
	at org.eclipse.scout.sdk.s2i.environment.OperationTask$run$2.invoke(OperationTask.kt:43)
	at org.eclipse.scout.sdk.s2i.environment.TransactionManager$Companion.callInExistingTransaction$lambda$0(TransactionManager.kt:87)
	at org.eclipse.scout.sdk.core.util.CoreUtils.callInContext(CoreUtils.java:281)
	at org.eclipse.scout.sdk.s2i.environment.TransactionManager$Companion.callInExistingTransaction(TransactionManager.kt:87)
	at org.eclipse.scout.sdk.s2i.environment.TransactionManager$Companion.callInNewTransaction(TransactionManager.kt:71)
	at org.eclipse.scout.sdk.s2i.environment.OperationTask.run(OperationTask.kt:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by nisrael** [comment]
I installed IntelliJ 2023.1.2 Ultimate and can confirm that the error does not occur there.

**Comment by nisrael** [comment]
Sorry. It happens with 2023.1.2 as well.

**Comment by mvilliger** [comment]
A new IJ plugin has been published. Could you please update and check if the issue is fixed?

**Comment by nisrael** [comment]
Unfortunately it is not fixed.

Plugin Version 13.0.0.231871615

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[ApplicationImpl pooled thread 4,4,main] 2092651117 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1835999687
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:205)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getSourceRootForFile(ProjectFileIndexImpl.java:199)
	at org.eclipse.scout.sdk.s2i.ExtensionsKt.resolveSourceRoot(Extensions.kt:111)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceInputWithIdea.getSourceFolderOf(DerivedResourceInputWithIdea.kt:39)
	at org.eclipse.scout.sdk.core.s.derived.DtoUpdateHandler.writeDerivedTypeOf(DtoUpdateHandler.java:50)
	at org.eclipse.scout.sdk.core.s.derived.DtoUpdateHandler.lambda$execute$0(DtoUpdateHandler.java:40)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at org.eclipse.scout.sdk.core.s.derived.DtoUpdateHandler.execute(DtoUpdateHandler.java:40)
	at org.eclipse.scout.sdk.core.s.derived.AbstractDerivedResourceHandler.apply(AbstractDerivedResourceHandler.java:43)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor$executeHandler$1.invoke(DerivedResourceManagerImplementor.kt:181)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor$executeHandler$1.invoke(DerivedResourceManagerImplementor.kt:179)
	at org.eclipse.scout.sdk.s2i.environment.TransactionManager$Companion.callInExistingTransaction$lambda$0(TransactionManager.kt:87)
	at org.eclipse.scout.sdk.core.util.CoreUtils.callInContext(CoreUtils.java:281)
	at org.eclipse.scout.sdk.s2i.environment.TransactionManager$Companion.callInExistingTransaction(TransactionManager.kt:87)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor.executeHandler(DerivedResourceManagerImplementor.kt:179)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor.executeAllHandlersAndWait(DerivedResourceManagerImplementor.kt:157)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor.performUpdateAsync(DerivedResourceManagerImplementor.kt:127)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor.access$performUpdateAsync(DerivedResourceManagerImplementor.kt:45)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor$scheduleUpdate$1.invoke(DerivedResourceManagerImplementor.kt:112)
	at org.eclipse.scout.sdk.s2i.derived.DerivedResourceManagerImplementor$scheduleUpdate$1.invoke(DerivedResourceManagerImplementor.kt:110)
	at org.eclipse.scout.sdk.s2i.environment.IdeaEnvironment$Factory$callInIdeaEnvironment$job$1$1.invoke(IdeaEnvironment.kt:75)
	at org.eclipse.scout.sdk.s2i.environment.IdeaEnvironment$Factory$callInIdeaEnvironment$job$1$1.invoke(IdeaEnvironment.kt:74)
	at org.eclipse.scout.sdk.s2i.environment.IdeaEnvironment$Factory.callInIdeaEnvironmentSync(IdeaEnvironment.kt:63)
	at org.eclipse.scout.sdk.s2i.environment.IdeaEnvironment$Factory$callInIdeaEnvironment$job$1.invoke(IdeaEnvironment.kt:74)
	at org.eclipse.scout.sdk.s2i.environment.IdeaEnvironment$Factory$callInIdeaEnvironment$job$1.invoke(IdeaEnvironment.kt:73)
	at org.eclipse.scout.sdk.s2i.environment.OperationTask$run$2.invoke(OperationTask.kt:44)
	at org.eclipse.scout.sdk.s2i.environment.OperationTask$run$2.invoke(OperationTask.kt:43)
	at org.eclipse.scout.sdk.s2i.environment.TransactionManager$Companion.callInExistingTransaction$lambda$0(TransactionManager.kt:87)
	at org.eclipse.scout.sdk.core.util.CoreUtils.callInContext(CoreUtils.java:281)
	at org.eclipse.scout.sdk.s2i.environment.TransactionManager$Companion.callInExistingTransaction(TransactionManager.kt:87)
	at org.eclipse.scout.sdk.s2i.environment.TransactionManager$Companion.callInNewTransaction(TransactionManager.kt:71)
	at org.eclipse.scout.sdk.s2i.environment.OperationTask.run(OperationTask.kt:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by mvilliger** [comment]
Thanks for testing. Issue is reproduced. We will come up with an update as soon as possible.

**Comment by mvilliger** [comment]
A new IJ plugin has been published. Could you please update and check if the issue is fixed?

**Comment by nisrael** [comment]
Hi Matthias,
It seems to work now. I altered some forms and forced an update of the derived resources: no error.
Thank you.

**Comment by mvilliger** [comment]
Thank you for reporting and testing :)
