### ISSUE TITLE
Scout SDK for IntelliJ: Fails to create project without warning if used with JDK21

### ISSUE THREAD

**Issue by padyx** [eclipse-scout/scout.sdk#32]
Hi all :)

I was trying to create a new Scout project in IntelliJ fails - but no error message is shown - probably the Java version is not supported.

### Steps to reproduce
1. Use "New project" from the "Welcome to IntelliJ" screen
2. Select Eclipse Scout Generator
3. Choose the JDK 21 installed on the system
4. Fill the parameters (I left the defaults, except changing the User Interface language to Java)
5. Click Next
6. Click Create

Expected: We're in an open project with the sample code filled.
Actual: We're back at the "Welcome to IntellIJ" screen, without any error message.

Based on the Stacktrace attached below there probably should be an error message telling me that my JDK version is not supported. 

"Workaround": Using Eclipse Temurin 17.0.13+11 allows me to create it successfully.

### Tech Info:
* JDK: Eclipse Temurin 21.0.5
* IntelliJ: IntelliJ IDEA 2024.3 (Community Edition)
* Scout Plugin Version: 13.0.0.241661015
* OS: Fedora Linux Workstation 41

### IntelliJ info
> Build #IC-243.21565.193, built on November 13, 2024
> Runtime version: 21.0.5+8-b631.16 amd64 (JCEF 122.1.9)
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> Toolkit: sun.awt.X11.XToolkit
> Linux 6.11.7-300.fc41.x86_64
> GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
> Memory: 2048M
> Cores: 16
> Registry:
>   ide.experimental.ui=true
>   i18n.locale=
> Non-Bundled Plugins:
>   org.eclipse.scout.sdk.s2i (13.0.0.241661015)
> Kotlin: 243.21565.193-IJ
> Current Desktop: GNOME

### IntelliJ log excerpt
```
2024-11-19 22:36:33,679 [  78947] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - Unhandled exception in [ComponentManager(ApplicationImpl@703834392), com.intellij.codeWithMe.ClientIdContextElementPrecursor@d9d97e2, CoroutineName(com.intellij.ide.actions.NewProjectActionCoroutineScopeHolder), Dispatchers.Default]
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction  or ReadAction; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#21,DefaultDispatcher-worker-4,5,main] 1248442874 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#55,AWT-EventQueue-0,6,main] 118265739
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:218)
	at com.intellij.util.concurrency.ThreadingAssertions.throwThreadAccessException(ThreadingAssertions.java:209)
	at com.intellij.util.concurrency.ThreadingAssertions.assertEventDispatchThread(ThreadingAssertions.java:78)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:238)
	at com.intellij.ui.messages.AlertDialog.<init>(AlertMessagesManager.kt:103)
	at com.intellij.ui.messages.AlertMessagesManager.showMessageDialog(AlertMessagesManager.kt:67)
	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:54)
	at com.jetbrains.rdserver.ui.BackendMessagesService.showMessageDialog(BackendMessagesService.kt:33)
	at com.intellij.openapi.ui.messages.MessagesService.showMessageDialog$default(MessagesService.kt:36)
	at com.intellij.openapi.ui.OkCancelDialogBuilder.show(MessageDialogBuilder.kt:201)
	at com.intellij.openapi.ui.OkCancelDialogBuilder.guessWindowAndAsk(MessageDialogBuilder.kt:196)
	at com.intellij.openapi.ui.Messages.showOkCancelDialog(Messages.java:538)
	at org.eclipse.scout.sdk.s2i.project.ScoutModuleBuilder.validate(ScoutModuleBuilder.kt:121)
	at com.intellij.ide.impl.NewProjectUtilKt.createProjectFromWizardImpl(NewProjectUtil.kt:219)
	at com.intellij.ide.impl.NewProjectUtilKt$createProjectFromWizardImpl$1.invokeSuspend(NewProjectUtil.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:277)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - Exception in thread "DefaultDispatcher-worker-4" com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction  or ReadAction; see https://jb.gg/ij-platform-threading for details
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - Current thread: Thread[#21,DefaultDispatcher-worker-4,5,main] 1248442874 (EventQueue.isDispatchThread()=false)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - SystemEventQueueThread: Thread[#55,AWT-EventQueue-0,6,main] 118265739
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:218)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.util.concurrency.ThreadingAssertions.throwThreadAccessException(ThreadingAssertions.java:209)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.util.concurrency.ThreadingAssertions.assertEventDispatchThread(ThreadingAssertions.java:78)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:238)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.ui.messages.AlertDialog.<init>(AlertMessagesManager.kt:103)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.ui.messages.AlertMessagesManager.showMessageDialog(AlertMessagesManager.kt:67)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:54)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.jetbrains.rdserver.ui.BackendMessagesService.showMessageDialog(BackendMessagesService.kt:33)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.openapi.ui.messages.MessagesService.showMessageDialog$default(MessagesService.kt:36)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.openapi.ui.OkCancelDialogBuilder.show(MessageDialogBuilder.kt:201)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.openapi.ui.OkCancelDialogBuilder.guessWindowAndAsk(MessageDialogBuilder.kt:196)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.openapi.ui.Messages.showOkCancelDialog(Messages.java:538)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at org.eclipse.scout.sdk.s2i.project.ScoutModuleBuilder.validate(ScoutModuleBuilder.kt:121)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.ide.impl.NewProjectUtilKt.createProjectFromWizardImpl(NewProjectUtil.kt:219)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at com.intellij.ide.impl.NewProjectUtilKt$createProjectFromWizardImpl$1.invokeSuspend(NewProjectUtil.kt)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:277)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
2024-11-19 22:36:33,683 [  78951]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ApplicationImpl@703834392), com.intellij.codeWithMe.ClientIdContextElementPrecursor@d9d97e2, CoroutineName(com.intellij.ide.actions.NewProjectActionCoroutineScopeHolder), StandaloneCoroutine{Cancelling}@3a4b4773, Dispatchers.Default]
```

**Comment by mvilliger** [comment]
Hi padyx, thx for reporting and sorry for the inconvenience. This seems to be an issue with the new IJ 2024.3 which changed the new project creation threading. We will look into it and provide a plugin update as soon as possible.

**Comment by mvilliger** [comment]
Hi padyx, a new plugin version has been published. Can you please update and try if it fixes this issue?

**Comment by padyx** [comment]
Hey @mvilliger! Thanks a lot for publishing that update so quickly.

I can confirm that with the Scout SDK plugin version 13.0.0.243260947, I see a message box now about the unsupported version. And both the Yes/No options also behave as expected.

Thanks for the quick fix!

Best regards!
